In [3]:
import numpy as np

# One dimensional array

In [6]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
arr_0_100 = np.arange(0, 101)
arr_0_100

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [11]:
# To check for even numbers
arr_even_num = np.arange(0, 101, 2)
arr_even_num

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [13]:
# Shape method 
arr_0_100.shape()

(101,)

# Two dimensional array

In [15]:
arr_2D = np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr_2D

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [18]:
# Three dimensional array
arr_3D = np.array([[1,2,3,4,5],[6,7,8,9,10], [11,12,13,14,15]])
arr_3D

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [19]:
arr_3D.shape

(3, 5)

In [21]:
arr_3D.size

15

In [29]:
arr_3D.reshape(15,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15]])

In [40]:
arr_2D_ex = np.array([np.arange(50, 71), np.arange(80, 101)])
arr_2D_ex

array([[ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,
         63,  64,  65,  66,  67,  68,  69,  70],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,
         93,  94,  95,  96,  97,  98,  99, 100]])

In [42]:
# Empty ARRAY

In [3]:
arr_zeros = np.zeros((2,3))
arr_zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [68]:
arr_ones = np.ones(4)*1
arr_ones

array([1., 1., 1., 1.])

In [61]:
arr_eyes = np.eye(4)*4
arr_eyes

array([[4., 0., 0., 0.],
       [0., 4., 0., 0.],
       [0., 0., 4., 0.],
       [0., 0., 0., 4.]])

In [63]:
# Write a array of 20 zeros
arr_zeros_20 = np.zeros(20)
arr_zeros_20

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [71]:
# Write a array of 20 elements of 10 in the form of 2D array
gen = np.array([np.ones(20)*10, np.ones(20)*10])
gen

array([[10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
        10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
        10., 10., 10., 10., 10., 10., 10.]])

In [74]:
np.linspace(50, 100)

array([ 50.        ,  51.02040816,  52.04081633,  53.06122449,
        54.08163265,  55.10204082,  56.12244898,  57.14285714,
        58.16326531,  59.18367347,  60.20408163,  61.2244898 ,
        62.24489796,  63.26530612,  64.28571429,  65.30612245,
        66.32653061,  67.34693878,  68.36734694,  69.3877551 ,
        70.40816327,  71.42857143,  72.44897959,  73.46938776,
        74.48979592,  75.51020408,  76.53061224,  77.55102041,
        78.57142857,  79.59183673,  80.6122449 ,  81.63265306,
        82.65306122,  83.67346939,  84.69387755,  85.71428571,
        86.73469388,  87.75510204,  88.7755102 ,  89.79591837,
        90.81632653,  91.83673469,  92.85714286,  93.87755102,
        94.89795918,  95.91836735,  96.93877551,  97.95918367,
        98.97959184, 100.        ])

In [77]:
# Create an array of 10 zeros
zero_10s = np.ones(10)*10
zer

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [78]:
!pip install pandas

In [79]:
# Get array dimension
arr_eyes.ndim

2

In [80]:
arr_2D.itemsize

8

In [81]:
arr_2D.size

15

In [84]:
arr_2D.dtype

dtype('int64')

In [85]:
e = np.array([1.0, 1.1, 1.2])

In [86]:
e.dtype

dtype('float64')

## Accessing/Changing specific elements; row, columns, etc. 

In [90]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [92]:
# Get specific element [row, column] using index
a[1, 5]

np.int64(13)

In [95]:
# Get specific element row
a[1,] # or [1, :]

array([ 8,  9, 10, 11, 12, 13, 14])

In [98]:
# Get specific element column
a[:, 2]

array([ 3, 10])

In [ ]:
# Numpy end

In [2]:
salary = np.array([5000, 4000, 1000])
tax = np.array([20, 15, 10])
profit = np.multiply(salary, tax)
profit

array([100000,  60000,  10000])

In [3]:
#discount = (profit * tax) * 100

In [5]:
discount = np.multiply(profit, tax) * 100

In [6]:
discount

array([200000000,  90000000,  10000000])

In [14]:
#id = np.array([001,002,003,004,005,006,007,008,009,010,011,012])
price = np.array([8000, 5000, 3000, 9000, 16000, 11000, 12000, 23000, 35000, 40000, 23000, 3500])

np.float64(7999.5)

In [29]:
salary = np.subtract(price[0], 0.5)
salary

np.float64(7999.5)

In [21]:
profit = np.subtract(price[0], salary)
profit

np.float64(0.5)

In [22]:
net_profit = np.subtract(salary, profit)
net_profit

np.float64(7999.0)

In [23]:
discount = np.add(net_profit, salary)
discount

np.float64(15998.5)

In [24]:
bill = np.add(price[0], salary)
bill

np.float64(15999.5)

In [31]:
total = salary + net_profit + profit + discount
total

np.float64(31997.5)

In [87]:
id = np.arange(100, 112)
price = np.array([8000, 5000, 3000, 9000, 16000, 11000, 12000, 23000, 35000, 40000, 23000, 3500])
ls_salary = []
percentage = 0.5
net_profit = np.array([])
ls_profit = []
discount = np.array([])
bill = np.array([])
total = np.array([])

for p in price:
    new_sal = p - percentage
    ls_salary.append(new_sal)

for i in range(0, len(price)):
    for s in salary:
        new_profit = price[i] - s
        ls_profit.append(new_profit)
        

salary = np.array(ls_salary)
profit = np.array(ls_profit)
print(salary)
print(profit)

[ 7999.5  4999.5  2999.5  8999.5 15999.5 10999.5 11999.5 22999.5 34999.5
 39999.5 22999.5  3499.5]
[ 5.00000e-01  3.00050e+03  5.00050e+03 -9.99500e+02 -7.99950e+03
 -2.99950e+03 -3.99950e+03 -1.49995e+04 -2.69995e+04 -3.19995e+04
 -1.49995e+04  4.50050e+03 -2.99950e+03  5.00000e-01  2.00050e+03
 -3.99950e+03 -1.09995e+04 -5.99950e+03 -6.99950e+03 -1.79995e+04
 -2.99995e+04 -3.49995e+04 -1.79995e+04  1.50050e+03 -4.99950e+03
 -1.99950e+03  5.00000e-01 -5.99950e+03 -1.29995e+04 -7.99950e+03
 -8.99950e+03 -1.99995e+04 -3.19995e+04 -3.69995e+04 -1.99995e+04
 -4.99500e+02  1.00050e+03  4.00050e+03  6.00050e+03  5.00000e-01
 -6.99950e+03 -1.99950e+03 -2.99950e+03 -1.39995e+04 -2.59995e+04
 -3.09995e+04 -1.39995e+04  5.50050e+03  8.00050e+03  1.10005e+04
  1.30005e+04  7.00050e+03  5.00000e-01  5.00050e+03  4.00050e+03
 -6.99950e+03 -1.89995e+04 -2.39995e+04 -6.99950e+03  1.25005e+04
  3.00050e+03  6.00050e+03  8.00050e+03  2.00050e+03 -4.99950e+03
  5.00000e-01 -9.99500e+02 -1.19995e+04 -2.

In [77]:
table = {
    "id": id,
    "price (le)": price,
    "salary": salary,
    "net_profit": net_profit,
    "profit": profit,
    "discount": discount,
    "bill": bill,
    "total": total
}

table

{'id': array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111]),
 'price (le)': array([ 8000,  5000,  3000,  9000, 16000, 11000, 12000, 23000, 35000,
        40000, 23000,  3500]),
 'salary': array([ 7999.5,  4999.5,  2999.5,  8999.5, 15999.5, 10999.5, 11999.5,
        22999.5, 34999.5, 39999.5, 22999.5,  3499.5]),
 'net_profit': array([], dtype=float64),
 'profit': array([], dtype=float64),
 'discount': array([], dtype=float64),
 'bill': array([], dtype=float64),
 'total': array([], dtype=float64)}

In [4]:
ar1 = np.arange(20, 81)

In [5]:
ar2 = np.arange(10,53)

In [6]:
ar3 = np.arange(70, 30, -1)

In [8]:
new_1d = np.concatenate([ar1, ar2, ar3])

In [9]:
new_1d

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70,
       71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 70, 69, 68, 67, 66, 65, 64, 63, 62, 61, 60, 59, 58, 57, 56,
       55, 54, 53, 52, 51, 50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39,
       38, 37, 36, 35, 34, 33, 32, 31])

In [21]:
new_reshape_ar1 = ar1.reshape(1, 61)

In [22]:
new_arshape_ar2 = ar2.reshape(1, 43)

ValueError: cannot reshape array of size 43 into shape (1,61)

In [34]:
new_2d = new_1d.reshape(12, 12)
new_2d

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43],
       [44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67],
       [68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 70, 69, 68, 67],
       [66, 65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55],
       [54, 53, 52, 51, 50, 49, 48, 47, 46, 45, 44, 43],
       [42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31]])

In [42]:
# Filter even numbers from new_2d array
filter_even = new_2d[new_2d % 2 == 0]

In [43]:
filter_even

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52,
       54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 10, 12, 14,
       16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48,
       50, 52, 70, 68, 66, 64, 62, 60, 58, 56, 54, 52, 50, 48, 46, 44, 42,
       40, 38, 36, 34, 32])